version: '3.8'
services:
  # Oracle Database
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: mortgage-oracle-db
    environment:
      ORACLE_PASSWORD: oracle123
      ORACLE_DATABASE: MORTGAGEDB
      ORACLE_USER: mortgage_user
      ORACLE_PASSWORD_USER: mortgage_pass
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      # - ./database/sample-data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql
      # - ./database/stored-procedures.sql:/docker-entrypoint-initdb.d/03-stored-procedures.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "mortgage_user/mortgage_pass@localhost:1521/MORTGAGEDB", "@/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - mortgage-network
    restart: unless-stopped

  # Backend Application
  mortgage-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mortgage-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
      DATABASE_URL: jdbc:oracle:thin:@oracle-db:1521:MORTGAGEDB
      DATABASE_USERNAME: mortgage_user
      DATABASE_PASSWORD: mortgage_pass
      JWT_SECRET: ${JWT_SECRET:-myVerySecretKeyForProductionUse123!}
      FILE_STORAGE_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
      - ./logs:/app/logs
    depends_on:
      oracle-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mortgage-network
    restart: unless-stopped

  # Frontend Application (React)
  mortgage-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mortgage-frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080/api
      REACT_APP_ENVIRONMENT: ${REACT_ENVIRONMENT:-development}
    ports:
      - "3000:3000"
    depends_on:
      - mortgage-backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mortgage-network
    restart: unless-stopped

  # Redis (for session management and caching)
  redis:
    image: redis:7-alpine
    container_name: mortgage-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mortgage-network
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local
  uploads_data:
    driver: local
  redis_data:
    driver: local

networks:
  mortgage-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16